# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev
r_packages:
  - covr
  - testthat
