# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev
r_packages:
  - covr
  - testthat
